import keyMirror from 'key-mirror';

export default keyMirror({
    SET_PLATFORM: null,
    SET_VERSION: null,

    SESSION_TOKEN_REQUEST: null,
    SESSION_TOKEN_SUCCESS: null,
    SESSION_TOKEN_FAILURE: null,
    RESPONSE_CANCEL_ORDER_LIST: null,

    DELETE_TOKEN_REQUEST: null,
    DELETE_TOKEN_SUCCESS: null,
    REALTIME:null,
    ON_LOGIN_STATE_CHANGE: null,
    PENDING_REALTIME_ORDER_LIST: null,
    LOGOUT: null,
    FISRT_LOGIN_SUCCESS: null,
    ON_AUTH_FORM_FIELD_CHANGE: null,
    SIGNUP_REQUEST: null,
    SIGNUP_SUCCESS: null,
    RESPONSE_UPDATE_USERLAYOUT: null,
    SIGNUP_FAILURE: null,
    RESEND_SMS_PASS_SUCESS: null,
    RESEND_SMS_PASS_FAIL: null,
    RESPONSE_ACCOUNT_ORDER_DETAIL: null,
    PENDING_BROADCAST_PRICE: null,
    LOGIN_REQUEST: null,
    LOGIN_SUCCESS: null,
    LOGIN_FAILURE: null,
    REJECT_ORDER_LIST: null,
    LOADING: null,
    RESPONSE: null,
    LOGOUT_REQUEST: null,
    LOGOUT_SUCCESS: null,
    LOGOUT_FAILURE: null,
    BROADCAST_PRICE: null,
    LOADING_WATCH_LIST:null,
    RESPONSE_WATCH_LIST:null,
    REALTIME_WATCH_LIST:null,
    LOADING_ORDER_LIST:null,
    RESPONSE_ORDER_LIST:null,
    LOADING_ADD_CODE:null,
    RESPONSE_ADD_CODE:null,
    REALTIME_ADD_CODE:null,
    REALTIME_ORDER_LIST:null,
    LOGGED_IN: null,
    LOGGED_OUT: null,

    LOADING_MODIFY_ORDER: null,
    RESPONSE_MODIFY_ORDER: null,
    RESPONSE_UPDATE_ORDER_MODIFY_ORDER: null,
    RESPONSE_ACCOUNT_MODIFY_ORDER: null,
    BROADCAST_PRICE__MODIFY_ORDER: null,

    SET_SESSION_TOKEN: null,

    RESET_PASSWORD_REQUEST: null,
    RESET_PASSWORD_SUCCESS: null,
    RESET_PASSWORD_FAILURE: null,

    GET_PROFILE_REQUEST: null,
    GET_PROFILE_SUCCESS: null,
    GET_PROFILE_FAILURE: null,

    ON_PROFILE_FORM_FIELD_CHANGE: null,
    RESEND_SMS_PASS: null,

    PROFILE_UPDATE_REQUEST: null,
    PROFILE_UPDATE_SUCCESS: null,
    PROFILE_UPDATE_FAILURE: null,

    SET_STATE: null,
    GET_STATE: null,
    SET_STORE: null,

    FORGOT_PASSWORD: null,
    LOGIN: null,
    REGISTER: null,

    LOADING_USERLAYOUT:null,


    UPDATEUSERINFO : null,
    LOADING_ORDER_DETAIL:null,
    RESPONSE_ORDER_DETAIL:null,
    BROADCAST_PRICE_ORDER_DETAIL:null,
    RESPONSE_NEW_ORDER_ORDER_DETAIL:null,

    REALTIME_OPEN_POSITION_INFO : null,
    LOADING_OPEN_POSITION_INFO : null,
    RESPONSE_OPEN_POSITION_INFO : null,
    PENDING_OPEN_POSITION_INFO : null,
});
