module.exports = {
    None: 0,
    CreateUserLogin: 1,
    ResetPassword: 3,
    RequestAll: 4,
    RequestById: 5,
    UpdateLakeRequire: 7,
    CreateLakeRequire: 6,
    GetListByMemberId: 9,
    ImportListLakeRequire: 10,
    GetByYear: 11,
    GetListAll: 12,
    CreateLakeAverageDaily: 13,
    UpdateLakeAverageDaily: 14,
    ImportLakeAverageDaily: 15,
    GetForCheckUpdate: 16,
    DeleteUserLogin: 17,
    Delete: 18,
    Insert: 19,
    Update: 2,
    GetByUserId: 21,
    GetCustom: 22,
    GetForDetail: 23,
    GetByTimeSession: 48,
    GetListActive: 511,
};
